project_id = "yxvuivtnyrcrtiqxhbkl"

[functions.ai-math-tutor]
verify_jwt = false

[functions.line-webhook]
verify_jwt = false

[functions.line-generate-link-code]
verify_jwt = false

[functions.send-line-message]
verify_jwt = false

[functions.generate-learning-path]
verify_jwt = false

[functions.upload-question-image]
verify_jwt = true

[functions.ai-generate-questions]
verify_jwt = true

[functions.ai-generate-from-template]
verify_jwt = true